// Question bank. {name} is replaced with the "star" player's name each round.
// Keep questions answerable in a few words so fuzzy matching works well.
module.exports = {
  sweet: [
    "What is {name}'s all-time favorite movie?",
    "Where would {name} love to go on a dream date?",
    "What is {name}'s ultimate comfort food?",
    "What song instantly puts {name} in a good mood?",
    "What is {name}'s biggest dream in life?",
    "What is {name}'s favorite season?",
    "What would {name} do with a completely free Sunday?",
    "What is {name}'s love language? (words, touch, gifts, time, acts)",
    "What is {name}'s favorite dessert?",
    "What is {name}'s favorite memory of you two?",
    "What is {name}'s biggest pet peeve?",
    "What is {name} most proud of?",
    "If {name} could have dinner with anyone, who would it be?",
    "What is {name}'s usual coffee or tea order?",
    "What does {name} do to unwind after a long day?",
    "What is {name}'s favorite holiday?",
    "What is {name} secretly afraid of?",
    "What did {name} want to be as a kid?",
    "What is the sweetest text {name} ever sent you?",
    "What small thing do you do that {name} loves most?",
  ],
  funny: [
    "What is {name}'s most-used emoji?",
    "If {name} were an animal, which one would they be?",
    "What is {name}'s guilty-pleasure TV show?",
    "What food could {name} eat every single day?",
    "What is {name}'s most irrational fear?",
    "What would {name}'s superhero name be?",
    "What is {name}'s go-to karaoke song?",
    "What is {name}'s worst habit?",
    "What is {name}'s most-used phone app?",
    "What would {name}'s autobiography be titled?",
    "What is {name}'s controversial food opinion?",
    "How long does {name} take to get ready to go out?",
    "What reality show would {name} definitely win?",
    "What is {name}'s hidden talent?",
    "What does {name} do when they think nobody is watching?",
    "What nickname would {name} give their car?",
    "What is {name}'s signature dance move called?",
    "What would {name} get 'arrested' for in a comedy film?",
    "What is {name}'s most dramatic overreaction?",
    "What is {name}'s go-to excuse for being late?",
  ],
  spicy: [
    "What is {name}'s idea of a perfect kiss?",
    "Where would {name} whisk you away for one night?",
    "What does {name} find most attractive about you?",
    "What song reminds {name} of you?",
    "What is {name}'s favorite way to spend a rainy day together?",
    "What does {name} miss most when you're apart?",
    "What is {name}'s favorite photo of the two of you?",
    "What would {name}'s dream proposal look like?",
    "What is {name}'s favorite date-night outfit on you?",
    "What is the boldest thing {name} has ever done for love?",
    "What nickname does {name} secretly love being called?",
    "What is {name}'s favorite thing about your smile?",
    "If {name} could relive one moment with you, which one?",
    "What is {name}'s love language in one word?",
    "What does {name} dream about for your future together?",
    "What is the most romantic thing {name} has ever planned?",
  ],
};
